accounts/urls.py
"""Defines URL patterns for accounts."""

from django.urls import path, include

from . import views


app_name = 'accounts'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

ll_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('ukraine_swu.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ukraine_swu/urls.py
"""Defines URL patterns"""

from django.urls import path

from . import views

app_name = 'ukraine_swu'
urlpatterns = [
    # Домашня
    path('', views.index, name='index'),
    
    # Сторінка категорії
    path('topic/<int:topic_id>/', views.topic, name='topic'),
    # Сторінка нового проекту
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Сторінка редагування проекту
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    #Сторінка проекту
    path('entry_page/<int:entry_id>/', views.entry_page, name='entry_page'),

 
]

accounts/models.py
from django.db import models

# Create your models here.

ukraine_swu/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

class Topic(models.Model):
    """Категорія проектів"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        
        return self.text
    
      
class Entry(models.Model):
    """Проекти"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    header = models.CharField(max_length=100)
    text = models.TextField()
    budget = models.IntegerField()

    rich_text = RichTextField(default="Детально опишіть ваш проект")
    image = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
       
        return f"{self.text[:50]}..."
"""Волонтери"""
class Volunteer(models.Model):
    name = models.CharField(max_length=100)
    photo = models.TextField()

ukraine_swu/forms.py
from django import forms

from .models import Topic, Entry
from ckeditor.widgets import CKEditorWidget

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['topic', 'header', 'image', 'budget', 'text',  'rich_text']
        labels = {'topic':'Категорія проекту','header':'Назва проекту', 'image':'Посилання на головне фото проекту', 'budget': 'Бюджет проекту, грн', 'text': 'Короткий опис проекту (до 120 символів)',  'rich_text': 'Детальний опис проекту'}
        widgets = {'text': forms.Textarea(attrs={'cols': 120, 'rows': 6, 'placeholder':"Коротко опишіть ваш проект (до 120 символів)", 'style':'resize:none;'}),
                   'topic':forms.Select(attrs={'cols': 50}),
                   'header': forms.Textarea(attrs={'cols': 120, 'rows': 3, 'placeholder':"Впишіть назву проекту", 'style':'resize:none;'}), 
                   'budget': forms.Textarea(attrs={'cols': 60, 'rows': 3, 'placeholder':"Впишіть очікувану вартість", 'style':'resize:none;'}),
                   'image': forms.Textarea(attrs={'cols': 120, 'rows': 3, 'placeholder':"Вставте посилання на ілюстрацію проекту", 'style':'resize:none;'}), 
                   'rich_text': CKEditorWidget()
                   }

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)
            return redirect('ukraine_swu:index')

    # Display a blank or invalid form.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

ukraine_swu/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry, Volunteer
from .forms import TopicForm, EntryForm


def index(request):
    """Домашня сторінка"""
    topics = Topic.objects.order_by('date_added')
    topic = Entry.objects.all()
    entries = topic.order_by('-date_added')
    people = Volunteer.objects.all()
    context = {'topic': topic,'topics': topics, 'entries': entries, 'people': people}
    return render(request, 'ukraine_swu/index.html', context)

def topic(request, topic_id):
    """Категорія і проекти"""
    topic = Topic.objects.get(id=topic_id)
    
    entries = topic.entry_set.order_by('-date_added')

    topics = Topic.objects.order_by('date_added')
    context = {'topic': topic, 'entries': entries, 'topics': topics}

    return render(request, 'ukraine_swu/topic.html', context)

#сторінка окремого проекту
def entry_page(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topics = Topic.objects.order_by('date_added')
    context = {'entry': entry, 'topics': topics}
    return render(request, 'ukraine_swu/entry_page.html', context)

@login_required    
def new_entry(request, topic_id):
    """новий проект"""
    topic = Topic.objects.get(id=topic_id)
    topics = Topic.objects.order_by('date_added')
    if request.method != 'POST':
        
        form = EntryForm()
    else:
     
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('ukraine_swu:topic', topic_id=topic_id)

 
    context = {'topic': topic, 'form': form, 'topics': topics}
    return render(request, 'ukraine_swu/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """редагувати проект."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    topics = Topic.objects.order_by('date_added')

    if request.method != 'POST':
    
        form = EntryForm(instance=entry)
    else:
     
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('ukraine_swu:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'form': form, 'topics': topics}
    return render(request, 'ukraine_swu/edit_entry.html', context)

ukraine_swu/templates/ukraine_swu/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Україна починається з тебе</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500&display=swap" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'ukraine_swu/styles.css' %}">
    <link rel="icon" type="image/png" href="{% static 'ukraine_swu/favicon.ico' %}">
   
  </head>
  <body>
    <button class="burger" onclick="toggleMenu()"></button>
    <div class="menu">
      <nav>
        <a href="{% url 'ukraine_swu:index' %}" style="animation-delay: 0.3s">Головна</a>
        {% for topic in topics %}
  
        <a href="{% url 'ukraine_swu:topic' topic.id %}" style="animation-delay: 0.3s">{{ topic.text }}</a>
  
        {% endfor %}
  
      </nav>
    </div>
    <div class="content">
      {% block content %}{% endblock content %}
    </div>
    <script type="text/javascript">
      const toggleMenu = () => document.body.classList.toggle("open");
    </script>
  </body>

  <footer>
    <div class="f1">
      <div id="copy">Виконав Саган Сергій учень 11-А класу Горохівського ліцею №1 ім. І. Я. Франка</div>
      <div id="socials">
        <p>Надіслати проект: </p>
        <a href="https://instagram.com"><img class='social-icon' src="{% static 'ukraine_swu/instagram.png' %}"></a>
        <a href="https://facebook.com"><img class='social-icon' src="{% static 'ukraine_swu/facebook.png' %}"></a>
        <a href="https://telegram.org"><img class='social-icon' src="{% static 'ukraine_swu/telegram.png' %}"></a>
        <a href="https://viber.com"><img class='social-icon' src="{% static 'ukraine_swu/viber.png' %}"></a>
        <a href="mailto:gorschool@gmail.com"><img class='social-icon' src="{% static 'ukraine_swu/email.png' %}"></a>
      </div>
    </div>
  </footer>
</html>

ukraine_swu/templates/ukraine_swu/edit_entry.html
{% extends "ukraine_swu/base.html" %}

{% block content %}


<section id="entry_page">
    <div id="edit-card">
      <div><h2>Редагувати проект:</h2></div>
      <form action="{% url 'ukraine_swu:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        <div id="form_elements">
          <div class="form-field">{{ form.topic }}</div>
          <div class="form-field">{{ form.header }}</div>
          <div class="form-field">{{ form.image }}</div>
          <div class="form-field">{{ form.budget }}</div>
          <div class="form-field">{{ form.text }}</div>
          <div class="form-field">{{ form.rich_text }}</div>
          {{ form.media }}
        
        </div>
        <button id="save-btn" name="submit">Зберегти</button>
      </form>
    </div>
</section> 

{% endblock content %}

ukraine_swu/templates/ukraine_swu/entry_page.html
{% extends 'ukraine_swu/base.html' %}
{% load static %}
{% block content %}

<section id="entry_page">
    <div id="card">
        <div id="entry_image"><img id="photo" src='{{ entry.image }}' /></div>
      <div id="content">  
        <div id="header"><h1>{{ entry.header }}</h1></div>
     
            <div id="entry-topic">Категорія: {{ entry.topic }}</div>
            <div id="entry-budget"><div id='coins'></div><div></div>{{ entry.budget }} грн</div>
            <div id="text">{{ entry.text }}</div>
            <div id="text">{{ entry.rich_text|safe }}</div>
            
        </div>
        <div ><a id="edit_entry" href="{% url 'ukraine_swu:edit_entry' entry.id %}">Редагувати</a></div>
    </div>
</section>  
{% endblock content %}

ukraine_swu/templates/ukraine_swu/index.html
{% extends 'ukraine_swu/base.html' %}
{% load static %}
{% block content %}
<html>
<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
</head>
<body>
<div class="all">  
  <div class="videoloop">
      <video src="{% static 'ukraine_swu/ukraine.mp4' %}" autoplay="autoplay" loop="loop" muted=""></video>
      <div id="title"><p>Україна починається з тебе</p></div>
  </div>

  <section id="projects">
    <div id="projects-title"><h1 >Проекти:</h1></div>
    <div class="entry-cards">
      {% for entry in entries %}
      <div class="entry-card">
          <div class="face face1">
              
              <div class="content">
                <img src="{{ entry.image }}">
                  <h3>{{ entry.header }}</h3>
              </div>
          </div>
          <div class="face face2">
              <div class="content">
                  <p>{{ entry.text }}</p>
                      <a href="{% url 'ukraine_swu:entry_page' entry.id %}">Більше</a>
              </div>
          </div>
      </div>
      {% endfor %}  
    </div>
  </section>

  <section id="people">
    <div id="people_header"><h1>Учасники проекту</h1></div>
    <div class="people-group">
      {% for person in people %}
        <div class="people-item" style="background-image: url('{{ person.photo }}')">
          <h1>{{ person.name }}</h1>
        </div>
      {% endfor %}
    </div>
  
      <script src='https://unpkg.co/gsap@3/dist/gsap.min.js'></script>
    
  </section>
</div>
</body>

<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/Swiper/6.4.5/swiper-bundle.min.js'></script>
<script >
  if (window.innerWidth > 740) { 
  const items = document.querySelectorAll('.people-item');
  const expand = (item, i) => {
    items.forEach((it, ind) => {
      if (i === ind) return;
      it.clicked = false;
    });
    gsap.to(items, {
      width: item.clicked ? '15vw' : '8vw',
      duration: 2,
      ease: 'elastic(1, .6)' });
  
  
    item.clicked = !item.clicked;
    gsap.to(item, {
      width: item.clicked ? '42vw' : '15vw',
      duration: 2.5,
      ease: 'elastic(1, .3)' });
  
  };
      
  items.forEach((item, i) => {
    item.clicked = false;
    item.addEventListener('click', () => expand(item, i));
  });
}
</script>

</html>
{% endblock content %}

ukraine_swu/templates/ukraine_swu/new_entry.html
{% extends "ukraine_swu/base.html" %}

{% block content %}

<section id="entry_page">
  <div id="edit-card">
    <div><h2>Додати проект:</h2></div>
    <form action="{% url 'ukraine_swu:new_entry' topic.id %}" method='post'>
      {% csrf_token %}
      <div id="form_elements">
        <div class="form-field">{{ form.topic }}</div>
        <div class="form-field">{{ form.header }}</div>
        <div class="form-field">{{ form.image }}</div>
        <div class="form-field">{{ form.budget }}</div>
       <div class="form-field">{{ form.text }}</div>
        <div class="form-field">{{ form.rich_text }}</div>
          {{ form.media }}
      </div>
      <button id="save-btn" name="submit">Зберегти</button>
    </form>
  </div>
</section> 

{% endblock content %}

ukraine_swu/templates/ukraine_swu/topic.html
{% extends 'ukraine_swu/base.html' %}

{% block content %}

<section id="entries-page">
  <div class="category-title"><h2>{{ topic.text }}</h2></div>
  {% if user.is_authenticated %}
    <div>
      <a id="edit_entry" href="{% url 'ukraine_swu:new_entry' topic.id %}">Новий проект</a>
    </div>
  {% endif %}
  <div id="grid-projects">
    {% for entry in entries %}
    <div class="card">
      <img src='{{ entry.image }}' />
      <div>
        <a class="entry_header" href="{% url 'ukraine_swu:entry_page' entry.id %}">{{ entry.header }}</a>
        <p>
          {{ entry.text|linebreaks }}
        </p>
        <button><a href="{% url 'ukraine_swu:entry_page' entry.id %}">Детальніше</a></button>
      </div>
    </div>
    {% empty %}
      <h1 id="no_proj">Немає проектів</h1>
    {% endfor %}

  </div>
</section>

{% endblock content %}